name: WorldBoundary
main: cn.lanink.worldboundary.WorldBoundary
version: "1.0.3"
api:
  - 1.0.0
load: POSTWORLD
author: "lt_name"

commands:
  boundary:
    description: 边界设置
    usage: /boundary
    permission: WorldBoundary.op
permissions:
  WorldBoundary.op:
    description: ""
    default: op