name: WorldBorder
main: cn.lanink.worldborder.WorldBorder
version: "1.2.2"
api: ["1.0.0"]
load: POSTWORLD
author: "LT_Name"

permissions:
  worldborder.admin:
    description: "WorldBorder插件管理员权限"
    default: op
  worldborder.leave:
    description: "WorldBorder离开边界权限"
    default: false