name: WorldBorder
main: cn.lanink.worldborder.WorldBorder
version: "1.0.3"
api: ["1.0.0"]
load: POSTWORLD
author: "lt_name"

commands:
  worldborder:
    description: 边界设置
    usage: /worldborder help
    permission: worldborder.op
permissions:
  worldborder.op:
    description: ""
    default: op