name: WorldBoundary
main: name.WorldBoundary.WorldBoundary
version: "1.0.1"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - AutoUpData

commands:
  boundary:
    description: 边界设置
    usage: /boundary
    permission: WorldBoundary.op
permissions:
  WorldBoundary.op:
    description: ""
    default: op